version: "3.9"
services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      TZ: ${TZ}
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL","pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 3s
      retries: 10

  api:
    image: ghcr.io/your-org/pgm-api:latest   # thay bằng image của bạn
    depends_on: 
      - db
    environment:
      DATABASE_URL: postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}?sslmode=disable
      API_BIND: ${API_BIND}
      API_JWT_SECRET: ${API_JWT_SECRET}
      API_ADMIN_EMAIL: ${API_ADMIN_EMAIL}
      API_ADMIN_PASSWORD: ${API_ADMIN_PASSWORD}
      TZ: ${TZ}
    ports:
      - "8082:8082"   # nội bộ, Nginx reverse
    healthcheck:
      test: ["CMD","wget","--no-verbose","--tries=1","--spider","http://localhost:8082/api/v1/admin/health"]
      interval: 10s
      timeout: 3s
      retries: 10

  nginx:
    image: nginx:1.27-alpine
    depends_on: 
      - api
    ports:
      - "${NGINX_LISTEN}:8080"
    volumes:
      - ./nginx/proxy-manager.conf:/etc/nginx/conf.d/default.conf:ro
      - ui_build:/usr/share/nginx/html:ro
    environment:
      TZ: ${TZ}

volumes:
  db_data:
  ui_build:
